name: CI 
on: [push] 
permissions:               
  contents: write

jobs: 
  build: 
   runs-on: ubuntu-latest 
   steps: 
   - uses: actions/checkout@v1 
   - name: Run make4ht 
     uses: xu-cheng/texlive-action/full@v1
     with:
          run: |
            set -euxo pipefail         # stop on first error, echo commands
            rm -rf out                 # clean previous artefacts (optional)
            make4ht -u -f html5 \
                    -j index \
                    -c .github/workflows/config.cfg \
                    -e .github/workflows/build.lua \
                    -d out 00-main.tex
   - name: Publish the web pages 
     uses:  peaceiris/actions-gh-pages@v3 
     with: 
       github_token: ${{ secrets.GITHUB_TOKEN }} 
       publish_dir: ./out
